###
GET http://localhost:3000/registro-empresas

###
POST http://localhost:3000/registro-empresas
Content-Type: application/json

{
    "nombre":"Las Yales SA",
    "nit":"54DS",
    "correo":"cristian@gmail.com",
    "contrasena":"fernando"
}

###
GET  http://localhost:3000/empresas

###
GET  http://localhost:3000/empresa/605fe3d169b0068109b1b113

###
DELETE  http://localhost:3000/empresa/eliminar/605fe36cca69688094a3b6f9

###
PUT  http://localhost:3000/empresa/editar/605fe3d169b0068109b1b113
Content-Type: application/json

{
    "nombre":"Pacific Black SA",
    "nit":"54DS",
    "correo":"cristian@gmail.com",
    "contrasena":"crisito"
}







###
POST http://localhost:3000/registro-ofertas
Content-Type: application/json
 
{
    "id_empresa":"6060dcbdb7438b14c0d3073e",
    "titulo":"Vendedor de droga",
    "descripcion": "Esta es una descripcion"
}

###
GET  http://localhost:3000/ofertas

###
GET  http://localhost:3000/oferta/6061086c7968904a1c0f173d

###
DELETE  http://localhost:3000/ofertas/eliminar/606108797968904a1c0f173e

###
PUT  http://localhost:3000/ofertas/editar/6061086c7968904a1c0f173d
Content-Type: application/json

{
    "id_empresa":"las tapas",
    "titulo":"Vendedor de vicio",
    "descripcion": "no descripcion"
}







###
POST http://localhost:3000/registro-empleados
Content-Type: application/json

{
    "nombre":"Fernando",
    "identificacion":"1006188941",
    "correo":"cristian@gmail.com",
    "contrasena":"mosquera"
}

###
GET  http://localhost:3000/empleados

###
GET  http://localhost:3000/empleado/606156c2b96a459d5dc64377

###
DELETE  http://localhost:3000/empleado/eliminar/606156c2b96a459d5dc64377

###
PUT  http://localhost:3000/empleado/editar/606156cdb96a459d5dc64378
Content-Type: application/json

{
    "nombre":"Cristiano Ronaldo",
    "identificacion":"1006188941",
    "correo":"cristian@gmail.com",
    "contrasena":"mosquera"
}
